### ISSUE TITLE
[BUG] Can't Install Module

### ISSUE THREAD

**Issue by GhostwheelX** [jsavko/inline-secrets#1]
There appears to be an issue with the link to the .json, would you mind looking into it, please?

I get the attached error when trying to install the module.

![image](https://user-images.githubusercontent.com/68725723/199090220-3560d7f3-f1a2-4181-b126-5eedd7b5fa00.png)

**Comment by jsavko** [comment]
What version of foundry are you running?

**Comment by GhostwheelX** [comment]
Just updated to v10.

**Comment by jsavko** [comment]
The manifest in that error is a v9 manifest that wont install on a v10 install.  Try Control+f5 then remove the module completely before reinstalling it

**Comment by GhostwheelX** [comment]
The module isn't installed, but I tried Ctrl + F5 and installing it, but it didn't do anything differently unfortunately.
Could it be that it's pointing at the wrong manifest file somewhere?

**Comment by jsavko** [comment]
Are you installing the module from the module browser?

**Comment by GhostwheelX** [comment]
Yes, I also tried to do so directly with the link available on the Foundry module page, but no luck there either.

**Comment by jsavko** [comment]
I updated the manifests, and tested installation with no issues. Try again and let me know if you run into issue

**Comment by GhostwheelX** [comment]
Installed perfectly now, thanks!
