### ISSUE TITLE
Hidden section shows on roll description chat text

### ISSUE THREAD

**Issue by kiloforce** [jsavko/inline-secrets#3]
I create an item with a "secet block" and a "@secret[]" inline:
![image](https://user-images.githubusercontent.com/433058/220425168-7aef0810-b4aa-4542-a534-7f213ec53574.png)

On the player view, the player who owns the item can see the "secret block" (_sadness_), but not the "@secret" (_PERFECT_)
![image](https://user-images.githubusercontent.com/433058/220425822-b4bb404a-5db6-48d2-84bf-8384070ad6d3.png)

But if the GM then clicks the "roll" button to display the item description to the group in the chat text, the "secret block" is hidden (_perfect_), but the "@secret" block shows up (_sadness_), and the players can hover to reveal it.  So neither secret option works in both situations (and for opposite reasons).  Could the "@secret" be hidden on the display chat text?
![image](https://user-images.githubusercontent.com/433058/220427734-e1459cb7-e283-41dd-8793-778d1483c3d7.png)
![image](https://user-images.githubusercontent.com/433058/220428373-251c05d1-2177-41fe-adff-0c8d6408b97a.png)
![image](https://user-images.githubusercontent.com/433058/220428437-0b16014c-397d-4826-94ef-fff2813155f2.png)

Using Foundry v10.291 with Inline Secrets 0.0.2.

**Comment by jsavko** [comment]
The inline secrets weren't desgined to be used with the chat cards.  I can look into adding that functionality.

The secret block is also core foundry and has nothing to do with inline secrets

**Comment by jsavko** [comment]
I've updated the functionality to work in chat messages as part of 0.0.3 which will release shortly
