### ISSUE TITLE
@ references break inline secrets if they are inside one

### ISSUE THREAD

**Issue by SovietVVinter** [jsavko/inline-secrets#5]
It seems like if I reference an item/compendium/scene/journal inside a secret block, the secret block does not work.

ex:
@secret[@Compendium[dnd5e.items.0E565kQUBmndJ1a2]{Dagger}]

**Comment by jsavko** [comment]
Noted. Will look into it later, but recursive Enrichers might be an issue

**Comment by jsavko** [comment]
It looks like this is due to how v10 handles TextEnrichers.  I am able to replicate the issue when using the short code, but manually copying the HTML into the secret block does work.  
Unfortunately there isn't anything that can be done at this time.
